apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dwk-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/FINDarkside/devops-with-kubernetes
  ref:
    branch: master
