apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-dep
  namespace: project
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: example-claim
      containers:
        - name: app2
          image: PROJECT/WEB
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: app2-api
          image: PROJECT/API
          envFrom:
          - secretRef:
              name: pg-password