apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: example-claim
      containers:
        - name: app2
          image: findarkside/app2:3511a0819ee6646dcd22d011
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: app2-api
          image: findarkside/app2-api:60f4d314b932bf6315b38236
          envFrom:
          - secretRef:
              name: pg-password