apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: findarkside/app2:eb023429fd769b45bc42f185220a8e56841ff966