apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-password
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCKl2McLhSj/S5fSaYHyobbb3IBdNuqANN/MCAZgTt9b3AiuDLBhggb5/2mrLEVH+zIW7VciCVrwacN+JUoTaxakzhrTxs21j/e4uH1c25VPXn4S3k6U2pO2Zf7Y2eNNVVIDAiNNijzKDByZsnAq83z3qQMqRZFFt53KjaoKRF9fiZfKemNL9PNtPar05+TVAPcQaPeG4XPOQsD/JTp4l1A7+3QQdc2fPX8+SXTYXovpcIbDv0ue+mbehcttC7J9rzcLDsz1lsDG15VRzniJE9YJihNzu8eHTVr4kuB1iwNuhZ2AfHrAlxaoy9YhNvtnvey0gLtU7KtX0ZG5WuwofPbHJz5yxOBeWHYsu5oamH5SxTxFvcAmubTa8DZCj2qL6coKXdIUDeCWsj/1NlcqN+pZRTwJdHR0vvf9lFaESTnIcLhLhCI0jMX3roiyakhQIVneOpWX3wvYUzcorl3vkzW40zRkPPI2himnmpHdUJV21K3asfoFgIlHxvGbR0KJE/EStNHTweekCoUH2h2UixUtm1s1Mx8mnFNT35QZIX6+SM4PVDVHDkidupX/1XjCad4mH06XiwnX/sKfQ5lFEEt2Fy3HELjrvEUTC6KfThyETc5D1WSc7y6hLZwku3/dttmw89PCnvGkGThA4EBlMzlJWGbLnJxVRdgVgvlF0rTJnPgFiMEhP7y8Ezr4qNOCzrvvXBlZzok
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pg-password
      namespace: project

