apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-password
  namespace: project
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAqm+61l8F5YjWCCtTlHSQjBF8Cw8agnvdyEGroJL2V5Jz7ZdNUjIhoj2W8/UJJvkgM/NoMdzF+XfUhJL8VspUldtrK0TSDOjAM3i9Ryh9WWfFRjcMytDr2hAUzb5V6FJm5d3z6KQoE3wSoMZ57cyrbepyOOY/agoouj70pQhvChM6Sv5N4lOp7WvIBH3ZKEVOMDW7Qn+WL6yqYUYw/BJvkrhrXoQY+mcCMyVUUd5qU9x7aDlm68fT2SDhT4adYJ588oeMawyBSM3/lsb1HuUBsCn6FLKyMFiCREgWmby310K6VMzeVlSeiLNvbO1q12RfXjDSaSGmqoQyWEuZCYv/Jcb+O//nqndg4sknHjiYkA/617ip6RcIkLv0ZrTxECy8+mao/ucR1Y4Z8/Y7GwEM4ZFG2P1+EjTteNFaLYKhyuyOTDpJ3GsGzHV5ISHf4INoRaOsLY3G2XE+gG+lwpyT6ZJnBOlm7trBYO4pyfC6Kt8/8DzhwXLlqWDBxj2pz/LlA4KFt48x1SQvHOJ/evWmi0YRt7Aqs1CdA+HADjN+FkCB/gn4NsSkLOyjccfAcaLccSYcNp0UyINg7lXSy0VFhMLRbe3tiWhxSH+OdY+7P5agAdY02k02Psd/7O1XgoQ7Tiz4CYEX2vHb/ZE52i0zTM+qzIMeJTRjpftiwpjylMQw2yQK7Q0smCYGbUAqYmG5ptPcdhAgD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pg-password
      namespace: project

