apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pg-password
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCjcmOUCx3tFFRdUwj6teszpttcTMHNh2SJwTiy3Op9QQakGMilcziqyWCbX9zv6fQREr2gyiNTe5v/fWcJtqLauqBYbT/ML4Lw/jRuy+1vM3uLleTqeJWRxG02tCbowIldBJhfLueprOYMq0PicI9ABahkkAo+WIQvvD32Nqzkd7AhuFy5d4vjzFj4ZsKp9o5Azsp+SJjEnJqV+gYvTh3rWSC0yThxT9rc0RHENhyy7Zw+b1x6B3yp8hYpgss+GPHFzmqCRS9PIbuX2rahaeYC+iRLEhwjhQraMzwRgUZxeOiY4exTXLDPR8AKVrMrlg1MQOrj8jNpWDgsImHST4hWfCDyUiJ0klJ9afkcniSidciUGCdctxs7Bqcge9j5nEbuRRvCTteZjX4H0V4NnfLss649lxObbzZGLP9//Adr8Vj2HhTxeZ/i/bbfpBkiFW3ms+0MU0cVXN7OOse9k6yzDLiREPbQkARE7WSXeJeu3Flddg82ZsFre7WrtmJRPEF+/hVVov7w0fwB6X9lGTJosx1OYphbRgyTeTcWFNCtpd/qS/OJNba5BF+6DqZ+I83bQwg1fOF33R9tJ38mPnDgvgzVe5+p2qkR1ecCkLGQNKMsStgJBRpxdXrbRRbeEjD5X/lxzyMGAK5abtukkoeY4J36yr/IRn0atLXMfPpFQYXjfYUm1t4kVgauCiFIFpvRrh+SuDkN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pg-password

