apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pg-password
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCgx8txZNOs4PRNn2SgbSahP/FL1jYYxB8VrZAGoNUHXYYw5t+mrHYJH/0dpjHME2Pypqm6/tNut3gdceoVOq2htx154RS6mzWIJv6dTTQjfJmLdgEhoW9rgkXMCPAAwjAlVycETQyWIuq4vm3IQ7C9HdOPBeGtGrwpIn7SWLwcB6rbKRQFBXlACqtGxPftua1M/iwnn7LCbR9sFtIgAJivQvS2Fwsse6m+yOwgh6SOB4u31B329bfmhKd9WhRbjLWlhamM8Qk3cQfMvDqkNlfkjim3eUxa/+gyC0tvSUYXz5JfVZOLOKGA/5F0VRK3Hrf4yQU4CbmM0UYk0Dzka9HdTIXimlJoHV8y+VxpOKoReukmqtDXS09YpnXx/xrAjpwJV1Nc7Tx1hX9lvJKKG23XyQujlad4bzkpAwUns+GBOMr2AQn4JuJ1fxe2AaXBwvFmpXChyHHbGMm1vYm+L8Iqa71QKHXTkKmQik4GfVwuwj7NjRSbq18ZPYtg+1K4kgnFamhGwb7Ubq4AQiFJOALoZL7gc4cIrycLLHwPuXi9DbKxB17hsfc93AUPAZacrBEoAhko50bHZGnvo9ihczlyXEDLWMZv5A3xcYCwmOw8SN86wC/HMPbiNx07HCdS35rrpakYSMMUgMrwt7+VZsPjFrMKC7uUQNeZP2vazf2z0vGa99chDbcqVPKWgsgf5i/Aka/EkJKL
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pg-password

