apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-api-key
  namespace: project2
spec:
  encryptedData:
    API_KEY: AgBGi26xiM1dIzVuUA4a8a6c1ItoQPVeb4jxtxMkbu0Ycx6QwF3+T9k07AJGmWPSGBDn97VQa7s/XQFqvYU0jEZ7H3tVACWphGzi4HsEODARMh2B1jLL6/V48w7RRZLyOQZB9JYXjvBLcCOI+u/ZbAHl+3/P+soFcwK8RZ293OA9SQwhgYJ5Q4QOF4MIliV2DuSLhK8MbCy6cU+3Qo0SiKj1iACdNznhEmWyntpF1tgGFh9qO+iX06wDyjxPGbuXVwCSB+ki12MroYJ4bKEPUWEkoP67dmJSZ1vjR43LvBXYsrqh6eUMojVf/Zxdn++DyyJIY2o08ZnUiftwywiiaTGLWqt8vTePLCcxam7fxEHvpC7zY5M8/LWD6ZCDm9MbD9aSjMyeLzixkhkD2jBbRYcmIcSAu17NbKtcqrp5k9wFb9jb55oO6FrAztO2YJWruU/YlJ7XPPNOJ3jz4FHSnxbwISg8H6mJRMCq8yaGPLi84/fxhnbJEm20X6izdy2oWkU24tNfAZjrF2bTM+KVFHdaYcuoXM4zWG4puYSRVEDKszUm9mm3DDz1Nu0p8Eq0iBdEnN3R3jok40NszrAARfSiL0L34NyQF1+2BJfqGIFj0Y1ti2ZajRrTe+1MipRMCIMlU1dUZmZ0z0Br+1nnNpEUh2AG5xowrLpNlQFXt0TBWffj7RsuEYD7+Np8keaEmZZbRP+0qLkwDhzF9t3zKttaphL1l5JMkLkCVWrmOeptUJdw/S2WGidLtP0eICqR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: telegram-api-key
      namespace: project2

