apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- manifests/deployment.yaml
resources:
- manifests/daily-todo.yaml
- manifests/rollout.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres.yaml
- manifests/pg-sealedsecret.yaml
- manifests/tg-sealedsecret.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
- manifests/persistentvolume.yaml
- manifests/postgres-storage.yaml
- manifests/broadcaster-deployment.yaml
images:
- name: PROJECT/API
  newName: findarkside/app2-api:20bd04c321fe80af48ccb4c3
- name: PROJECT/BROADCASTER
  newName: findarkside/app2-broadcaster
  newTag: d120450a436ddf1ccec91fb1d28f175f098a461c
- name: PROJECT/DAILY_TODO
  newName: findarkside/app2-daily-todo
  newTag: f8c8770f653f8e310395b7bad4c188a1a80e4f0a
- name: PROJECT/WEB
  newName: findarkside/app2
  newTag: 2233065ea9b122fe6c82496252a561600fb41b48
