apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/daily-todo.yaml
#- manifests/deployment.yaml
- manifests/rollout.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres.yaml
- manifests/sealedsecret.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
images:
- name: PROJECT/WEB
  newName: findarkside/app2:5ca663e68a022c27a59312a5
- name: PROJECT/API
  newName: findarkside/app2-api:7823a81f8ae68a069cb45fd1
- name: PROJECT/DAILY_TODO
  newName: findarkside/app2-daily-todo:5e7ab1fd5db5d857558edaac
