apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#- manifests/deployment.yaml
resources:
- manifests/daily-todo.yaml
- manifests/rollout.yaml
- manifests/ingress.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres.yaml
- manifests/pg-sealedsecret.yaml
- manifests/tg-sealedsecret.yaml
- manifests/service.yaml
- manifests/analysistemplate.yaml
- manifests/persistentvolume.yaml
- manifests/postgres-storage.yaml
- manifests/broadcaster-deployment.yaml
images:
- name: PROJECT/WEB
  newName: findarkside/app2:3173e9c142920f945d841550
- name: PROJECT/API
  newName: findarkside/app2-api:20bd04c321fe80af48ccb4c3
- name: PROJECT/DAILY_TODO
  newName: findarkside/app2-daily-todo:5e7ab1fd5db5d857558edaac
- name: PROJECT/BROADCASTER
  newName: findarkside/app2-broadcaster:1903afc937619d5a05642984
namespace: project2
