apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: example-claim
      containers:
        - name: app3
          image: findarkside/app3-hash:2212d43153ad0822abc556ea
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files