apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app1-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app1-svc
          servicePort: 2346
      - path: /pingpong
        backend:
          serviceName: app3-svc
          servicePort: 2347