apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-password
  namespace: main-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgADRg5cHS/q2cb36l1YLO6BpVf0ddDd912LFFqRAfcx8nGRRYRS12wLCnBj0oAgh1kv3TSTKVohMkmkJWFUGGPF3AntNd9DdVwAxnNLL+G1IapycoCYZSPnvK64QI9V3h84D30P/XztZrAW/yr11V0w2hgQRAU/sWfrxjozUXOWmCnaT1MfrcjiyiGNaxWmqdlrn4I1sQoi2fQ7D8uexqVxH7F1lz3VgP8Y7WisXcrcLTHe65JugWWqlkSE9TZ5njna9O64NNR8j7KiLbsPuLZoIVimWJTW9SvpMCwSLQ3SCNxZmlMj39taMVprCFtlSspFi680w9sUGW61yKvjeXH9SCvBt1JNnE9u0NQZxoRpwb0liHp6o/OYD3V0LcBQCAmc7uo1HBFruTSURU1HFC/WN8xtw5G6FxByk/Yx5wOdp0a5EensZULZAvp8Hk0DvHIYNhfpFKBqfHyymHTN3aojbCp4U1ptKvfiNJYCUrZDsI+y20FBuumb6IKIxBpoLfwGuO9OKmQRXfUKfjlwrCUNlWWxVwNIbEk4Y1qCo4J0yoq6wVPMo2tJXi6SWc9SoOz3IUCRMfrIx1mcce/E2djqhPFsUCrBKiqYbkTxR8tZ9VmhE5AhUhhfemXsSqbAs4GZxJsTLUX/XDiZl/DRiLsbLrsMFM5+S58CxQB4WsAvyutE5yKk42m3nyQTWsyXolSExGr+cXl6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pg-password
      namespace: main-app

