apiVersion: v1
kind: Service
metadata:
  name: app3-svc
spec:
  type: ClusterIP
  selector:
    app: app3
  ports:
    - name: external
      port: 2347
      protocol: TCP
      targetPort: 3000
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
