apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
  namespace: project
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 30s
    successCondition: result < 0.01
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1624-prometheus.prometheus.svc.cluster.local:9090 # DNS name for my Prometheus, find yours with kubectl describe svc ...
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[1m])))
