apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-todo
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-todo
            image: PROJECT/DAILY_TODO
            env:
            - name: URL
              value: "http://app2-svc:2348/todos"
          restartPolicy: OnFailure
