apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app3-svc
  namespace: main-app
spec:
  template:
    metadata:
      name: app3-svc-dwk-v6
      annotations:
        autoscaling.knative.dev/minScale: "3"
    spec:
      containers:
        - image: findarkside/app3:97c485400ee2a29ade076fa3
          envFrom:
          - secretRef:
              name: pg-password

