apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dep
  namespace: main-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: example-claim
      containers:
        - name: app1-timestamp
          image: findarkside/app1-timestamp:c23901d77d04d9aff1dbea94
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: app1-hash
          image: findarkside/app1-hash:0e88d06ed139fccadc495764
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: example-config
                  key: MESSAGE