apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: findarkside/app1:14833010a9ca747d56d8a426616b04c80d2e7f59