name: Release application

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: gcloud --quiet auth configure-docker
    
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Create image name and tag
      run: |-
        echo "name=WEB_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/app2/web:${GITHUB_REF#refs/heads/}-$GITHUB_SHA >> $GITHUB_ENV"
        echo "name=API_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/app2/api:${GITHUB_REF#refs/heads/}-$GITHUB_SHA >> $GITHUB_ENV"
        echo "name=DAILY_TODO_WITH_TAG::gcr.io/${{ secrets.GKE_PROJECT }}/app2/daily_todo:${GITHUB_REF#refs/heads/}-$GITHUB_SHA >> $GITHUB_ENV"
        echo "{{ env.$WEB_WITH_TAG }}"

    - name: Build
      run: |-
        docker build --tag "{{ env.$WEB_WITH_TAG }}" ./app2/web
        docker build --tag "{{ env.$API_WITH_TAG }}" ./app2/api
        docker build --tag "{{ env.$DAILY_TODO_WITH_TAG }}" ./app2/daily-todo
      working-directory: ./app2

    - name: Publish
      run: |-
        docker push "${{ env.WEB_WITH_TAG }}"
        docker push "${{ env.API_WITH_TAG }}"
        docker push "${{ env.DAILY_TODO_WITH_TAG}}"

    - name: Set up Kustomize
      working-directory: ./app2
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy
      working-directory: ./app2
      run: |-
        ./kustomize edit set image PROJECT/WEB=${{ env.WEB_WITH_TAG }}
        ./kustomize edit set image PROJECT/API=${{ env.API_WITH_TAG }}
        ./kustomize edit set image PROJECT/DAILY_TODO=${{ env.DAILY_TODO_WITH_TAG }}
        kubectl apply -k .
        kubectl rollout status deployment app2-dep -n project
        


