name: Release-app2-daily-todo

on:
  push:
    branches:
      - master
    paths:
      - 'app2/**/daily-todo'
      - '.github/workflows/release-app2-daily-todo.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build and push
    - name: Publish web app
      uses: docker/build-push-action@v1
      with:
        repository: findarkside/app2-daily-todo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: app2/daily-todo

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: app2/
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: app2/
      run: |-
        ./kustomize edit set image PROJECT/DAILY_TODO=findarkside/app2-daily-todo:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'app2/kustomization.yaml'
        message: New version release for app2-daily-todo ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
